const E=new TextEncoder(),RL=new Map();
const APP_ORIGIN="https://lumen-arcana.kraplenii.workers.dev";
const APP_URL=`${APP_ORIGIN}/?v=telegram-sync2`;
const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
const clean=(v,n=300)=>String(v??"").trim().slice(0,n);
async function body(r){const t=await r.text();if(E.encode(t).length>49152)throw Object.assign(new Error("body_too_large"),{status:413});try{return JSON.parse(t||"{}")}catch{throw Object.assign(new Error("invalid_json"),{status:400})}}
function allow(r,p){const ip=r.headers.get("cf-connecting-ip")||"unknown",k=ip+":"+p,n=Date.now(),b=RL.get(k);if(!b||n-b.t>60000){RL.set(k,{t:n,c:1});return true}return ++b.c<=30}
async function hmac(k,m){const key=await crypto.subtle.importKey("raw",k,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return crypto.subtle.sign("HMAC",key,E.encode(m))}
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");
export async function verifyTelegramInitData(d,t,max=86400){if(!d||!t)return false;const p=new URLSearchParams(d),h=p.get("hash"),a=Number(p.get("auth_date"));if(!h||!a||Math.abs(Date.now()/1000-a)>max)return false;p.delete("hash");p.delete("signature");const s=[...p].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n"),sk=await hmac(E.encode("WebAppData"),t),calc=hex(await hmac(new Uint8Array(sk),s));if(calc.length!==h.length)return false;let dff=0;for(let i=0;i<calc.length;i++)dff|=calc.charCodeAt(i)^h.toLowerCase().charCodeAt(i);return dff===0}
const crisis=/(суїцид|самогуб|убить себя|самоубий|не хочу жить|не хочу жити|kill myself|suicide|self.?harm)/i,medical=/(діагноз|лікуван|операц|вагітн|пологи|хвороб|рак|pregnan|diagnos|surgery|disease)/i,financial=/(кредит|лотере|інвест|акці|крипт|ставк|вигра|loan|lottery|invest|crypto|bet)/i,legal=/(суд|вирок|арешт|поліці|закон|court|arrest|legal)/i;
const risk=q=>crisis.test(q)?"crisis":medical.test(q)?"medical":financial.test(q)?"financial":legal.test(q)?"legal":"normal";
const kw=v=>Array.isArray(v)?v.slice(0,6).map(x=>clean(x,40)).filter(Boolean):[];
const arr=v=>Array.isArray(v)?v.slice(0,3).map(x=>clean(x,60)).filter(Boolean):[];
function pctx(i,uk){const p=i.personalization;if(!p?.enabled)return"";const bits=[];if(p.themes?.length)bits.push(uk?`у збереженій історії повторюються теми: ${p.themes.join(", ")}`:`saved history repeats these themes: ${p.themes.join(", ")}`);if(p.repeatedCards?.length)bits.push(uk?`повторювані карти: ${p.repeatedCards.join(", ")}`:`recurring cards: ${p.repeatedCards.join(", ")}`);if(p.sunSign)bits.push(uk?`сонячний знак у локальному натальному профілі: ${p.sunSign}`:`Sun sign in the local natal profile: ${p.sunSign}`);return bits.length?(uk?` Персональний контекст: ${bits.join("; ")}. Використовуй це лише як контекст із локальних даних, а не як факт поза ними.`:` Personal context: ${bits.join("; ")}. Use this only as context from local saved data, not as a fact beyond it.`):""}
function fallback(i,r){const uk=i.language==="uk",names=i.cards.map(c=>c.name||c.keywords?.[0]).filter(Boolean),arc=names.length>1?names.slice(0,-1).join(", ")+" → "+names.at(-1):names[0],base=(uk?`Карти вказують на послідовність: ${arc}. Сприймай це як спосіб осмислення, а не як незмінне передбачення.`:`The cards point to this sequence: ${arc}. Treat it as a reflective lens, not a fixed prediction.`)+pctx(i,uk),guide=uk?"Назви одну дію, яку контролюєш сьогодні, і одне припущення, якому ще бракує доказів.":"Name one action you control today and one assumption that still needs evidence.",caution=uk?`Не дозволяй запитанню «${i.question}» перетворювати невизначеність на вигадану певність.`:`Do not let the question “${i.question}” turn uncertainty into certainty.`;return{blocked:false,risk:r,source:"local",title:uk?(i.spread==="single"?"Фокус розкладу":"Дуга розкладу"):(i.spread==="single"?"Focus of the reading":"The arc of the reading"),cards:i.cards.map((c,n)=>({card:c.name||`Card ${n+1}`,position:c.position||`Position ${n+1}`,observation:`${c.name||`Card ${n+1}`} · ${c.orientation==="reversed"?(uk?"перевернута":"reversed"):(uk?"пряма":"upright")}${c.symbol?` · ${c.symbol}`:""}`,symbolism:kw(c.keywords).join(" · ")||(uk?"Символічну тему варто уточнити через власне спостереження.":"The symbolic theme needs your own observation."),positionMeaning:c.position||`Position ${n+1}`,context:base,practice:guide})),synthesis:base,caution:caution+(r!=="normal"?(uk?` Запит належить до сфери ${r}; Таро не замінює професійне рішення.`:` This is a ${r} topic; Tarot does not replace professional advice.`):"")}}
function crisisReply(l){return l==="uk"?{blocked:true,risk:"crisis",source:"safety",title:"Цей запит не варто розкладати на Таро",message:"LUMEN ARCANA не робить прогнозів щодо самозагрози.",nextStep:"Звернися до людини або служби, яка може надати негайну реальну підтримку. Якщо є безпосередня небезпека — звернися до екстрених служб."}:{blocked:true,risk:"crisis",source:"safety",title:"This should not be handled as a Tarot reading",message:"LUMEN ARCANA does not make self-harm predictions.",nextStep:"Contact immediate real-world support. If there is immediate danger, contact emergency services."}}
function outText(p){if(typeof p?.output_text==="string")return p.output_text;for(const x of p?.output||[])for(const c of x?.content||[])if(typeof c?.text==="string")return c.text;return""}
async function ai(i,r,e){if(!e.OPENAI_API_KEY)return null;const schema={type:"object",additionalProperties:false,required:["title","cards","synthesis","caution"],properties:{title:{type:"string"},cards:{type:"array",items:{type:"object",additionalProperties:false,required:["card","position","observation","symbolism","positionMeaning","context","practice"],properties:{card:{type:"string"},position:{type:"string"},observation:{type:"string"},symbolism:{type:"string"},positionMeaning:{type:"string"},context:{type:"string"},practice:{type:"string"}}}},synthesis:{type:"string"},caution:{type:"string"}}};const q=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${e.OPENAI_API_KEY}`},body:JSON.stringify({model:e.OPENAI_MODEL||"gpt-5.6-luna",store:false,input:[{role:"developer",content:`Write a concise psychologically safe Tarot reflection in the requested language. Use observation -> symbolism -> spread position -> user context -> practical action. Personalization, when present, comes only from the user's saved local app data: refer to it cautiously (for example, "у твоїй збереженій історії повторюється...") and never infer facts that are not present. Never claim certainty or predict death, pregnancy, crime, medical/legal/financial outcomes. Risk=${r}. Return JSON only.`},{role:"user",content:JSON.stringify(i)}],text:{format:{type:"json_schema",name:"tarot_reading_v2",strict:true,schema}}})});if(!q.ok)throw new Error(`openai_${q.status}`);return{blocked:false,risk:r,source:"ai",...JSON.parse(outText(await q.json()))}}
async function tg(m,b,e){if(!e.TELEGRAM_BOT_TOKEN)throw new Error("telegram_not_configured");const q=await fetch(`https://api.telegram.org/bot${e.TELEGRAM_BOT_TOKEN}/${m}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b||{})}),x=await q.json();if(!x.ok)throw new Error(`${m}: ${x.description||q.status}`);return x.result}
const menuButton=()=>({type:"web_app",text:"LUMEN ARCANA",web_app:{url:APP_URL}});
async function syncTelegramMenu(chatId,e){const jobs=[tg("setChatMenuButton",{menu_button:menuButton()},e)];if(chatId)jobs.push(tg("setChatMenuButton",{chat_id:chatId,menu_button:menuButton()},e));const result=await Promise.allSettled(jobs);for(const x of result)if(x.status==="rejected")console.error("setChatMenuButton",x.reason);return result.some(x=>x.status==="fulfilled")}
let routeSyncAt=0,routeSyncPromise=null;
async function ensureTelegramRouting(e){if(!e.TELEGRAM_BOT_TOKEN||!e.TELEGRAM_WEBHOOK_SECRET)return false;const now=Date.now();if(routeSyncPromise)return routeSyncPromise;if(now-routeSyncAt<600000)return true;routeSyncPromise=(async()=>{const desired=`${APP_ORIGIN}/telegram/webhook`;let info=null;try{info=await tg("getWebhookInfo",{},e)}catch(err){console.error("getWebhookInfo",err)}if(info?.url!==desired){await tg("setWebhook",{url:desired,secret_token:e.TELEGRAM_WEBHOOK_SECRET,allowed_updates:["message"],drop_pending_updates:false},e)}await tg("setChatMenuButton",{menu_button:menuButton()},e);routeSyncAt=Date.now();return true})().catch(err=>{console.error("telegram routing sync",err);return false}).finally(()=>{routeSyncPromise=null});return routeSyncPromise}
async function update(u,r,e){const m=u?.message;if(!m?.chat?.id)return;const c=String(m.text||"").split(/\s+/)[0].split("@")[0].toLowerCase(),uk=m.from?.language_code==="uk",url=APP_URL;if(c==="/start"||c==="/app"){await syncTelegramMenu(m.chat.id,e);await tg("sendMessage",{chat_id:m.chat.id,text:uk?"LUMEN ARCANA — актуальна Premium Beta версія. Усі beta-функції відкриті без оплати.":"LUMEN ARCANA — current Premium Beta version. All beta features are free.",reply_markup:{inline_keyboard:[[{text:uk?"Відкрити актуальну LUMEN ARCANA":"Open current LUMEN ARCANA",web_app:{url}}]]}},e)}else if(c==="/help"){await syncTelegramMenu(m.chat.id,e);await tg("sendMessage",{chat_id:m.chat.id,text:"Commands: /start · /app · /help"},e)}else{await syncTelegramMenu(m.chat.id,e)}}
async function api(r,e,p){if(!allow(r,p))return J({error:"rate_limited"},429);if(r.method==="GET"&&p==="/api/health")return J({ok:true,app:"LUMEN ARCANA",version:"2.2.2-webhook-selfheal",runtime:"cloudflare-worker",appUrl:APP_URL,webhookTarget:`${APP_ORIGIN}/telegram/webhook`,ai:!!e.OPENAI_API_KEY,telegram:!!e.TELEGRAM_BOT_TOKEN,webhookSecret:!!e.TELEGRAM_WEBHOOK_SECRET});if(r.method==="POST"&&p==="/api/beta/verify"){const{code}=await body(r),ok=new Set((e.BETA_CODES||"LUMEN-BETA").split(",").map(x=>x.trim().toUpperCase())).has(clean(code,64).toUpperCase());return J({accepted:ok},ok?200:403)}if(r.method==="POST"&&p==="/api/telegram/verify"){const b=await body(r),ok=await verifyTelegramInitData(clean(b.initData,8192),e.TELEGRAM_BOT_TOKEN);return J({ok},ok?200:401)}if(r.method==="POST"&&p==="/api/interpret"){const b=await body(r),question=clean(b.question,500),language=clean(b.language,12)||"uk",rr=risk(question);if(rr==="crisis")return J(crisisReply(language));const cards=Array.isArray(b.cards)?b.cards.slice(0,10).map(c=>({name:clean(c.name,80),position:clean(c.position,120),symbol:clean(c.symbol,8),orientation:c.orientation==="reversed"?"reversed":"upright",keywords:kw(c.keywords)})):[];if(!cards.length)return J({error:"cards_required"},400);const rawP=b.personalization&&typeof b.personalization==="object"?b.personalization:{},personalization={enabled:rawP.enabled===true,historyCount:Math.max(0,Math.min(9999,Number(rawP.historyCount)||0)),favoriteCount:Math.max(0,Math.min(9999,Number(rawP.favoriteCount)||0)),sunSign:clean(rawP.sunSign,30),themes:arr(rawP.themes),repeatedCards:arr(rawP.repeatedCards)};const i={language,question,spread:clean(b.spread,64)||"themed",mode:b.mode==="pro"||b.mode==="professional"?"pro":"beginner",cards,personalization};try{return J(await ai(i,rr,e)||fallback(i,rr))}catch(err){console.error(err);return J(fallback(i,rr))}}return J({error:"not_found"},404)}
async function webhook(r,e){if(r.method!=="POST")return new Response("Method Not Allowed",{status:405});if(!e.TELEGRAM_BOT_TOKEN||!e.TELEGRAM_WEBHOOK_SECRET)return J({error:"telegram_not_configured"},503);if((r.headers.get("x-telegram-bot-api-secret-token")||"")!==e.TELEGRAM_WEBHOOK_SECRET)return J({error:"unauthorized"},401);await update(await body(r),r,e);return J({ok:true})}
async function setup(r,e){if(r.method!=="POST")return new Response("Method Not Allowed",{status:405});if(!e.TELEGRAM_BOT_TOKEN||!e.TELEGRAM_WEBHOOK_SECRET||!e.ADMIN_SECRET)return J({error:"setup_not_configured"},503);if((r.headers.get("authorization")||"")!==`Bearer ${e.ADMIN_SECRET}`)return J({error:"unauthorized"},401);const webhookUrl=`${APP_ORIGIN}/telegram/webhook`,[webhookResult,menuResult]=await Promise.all([tg("setWebhook",{url:webhookUrl,secret_token:e.TELEGRAM_WEBHOOK_SECRET,allowed_updates:["message"],drop_pending_updates:false},e),tg("setChatMenuButton",{menu_button:menuButton()},e)]);return J({ok:true,webhookUrl,appUrl:APP_URL,menuButtonSynced:true,webhookResult,menuResult})}
function sec(x){const h=new Headers(x.headers);h.set("x-content-type-options","nosniff");h.set("referrer-policy","strict-origin-when-cross-origin");h.set("permissions-policy","camera=(), microphone=(), geolocation=()");return new Response(x.body,{status:x.status,statusText:x.statusText,headers:h})}
export default{async fetch(r,e,ctx){const u=new URL(r.url);try{if(u.pathname.startsWith("/api/")){if(u.pathname==="/api/health")ctx?.waitUntil?.(ensureTelegramRouting(e));return api(r,e,u.pathname)}if(u.pathname==="/telegram/webhook")return webhook(r,e);if(u.pathname==="/telegram/setup")return setup(r,e);if((u.pathname==="/"||u.pathname==="/index.html"))ctx?.waitUntil?.(ensureTelegramRouting(e));if(!e.ASSETS)return new Response("Assets binding missing",{status:503});return sec(await e.ASSETS.fetch(r))}catch(x){console.error(x);return J({error:x?.message||"worker_error"},x?.status||500)}}};